spring.application.name= customer
server.port = 8080

spring.profiles.active=dev



management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=transaction-group
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


#eureka.client.service-url.defaultZone= http://eureka-server:8761/eureka/