CREATE DATABASE IF NOT EXISTS customer;
CREATE DATABASE IF NOT EXISTS hotelmanagement;
CREATE DATABASE IF NOT EXISTS reservation;
CREATE DATABASE IF NOT EXISTS payment;
CREATE DATABASE IF NOT EXISTS notification;
